services:
  database:
    build:
      context: .
      dockerfile: dockers/database.dockerfile
    environment:
      # Secure credential handling - in .env file
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-scambot_db}
      - MYSQL_USER=${MYSQL_USER:-scambot_user}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: on-failure
    networks:
      service_net:
        ipv4_address: 172.18.0.2

  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: on-failure
    networks:
      service_net:
        ipv4_address: 172.18.0.3

  backend:
    build:
      context: .
      dockerfile: dockers/backend.dockerfile
    ports:
      - "8000:8000"
    restart: on-failure
    networks:
      service_net:
        ipv4_address: 172.18.0.4
    depends_on:
      - database
      - redis

  frontend:
    build:
      context: .
      dockerfile: dockers/frontend.dockerfile
    ports:
      - "3000:3000"
    restart: on-failure
    networks:
      service_net:
        ipv4_address: 172.18.0.5
    depends_on:
      - backend

volumes:
  mysql_data:
    driver: local

networks:
  service_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
